#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi



# Source the script that generates the info in the dwm menu bar, since it's basically its own module:
source /home/lys/sh/X_infobar.sh &

# Set keyboard layout to danish. Probably suboptimal, but it works.
setxkbmap dk

# Autocutsel syncronisation between primary selection and the clipboard.

if [ -x /usr/bin/autocutsel ]; then
    #this will keep the clipboard in sync
    #   with the primary buffer
    autocutsel -selection CLIPBOARD -fork

    #this will keep the primary in sync
    #   with the clipboard buffer
    autocutsel -selection PRIMARY -fork
fi

# Enable Terminus & artwiz in Arch ( / dwm ):
xset +fp /usr/share/fonts/local
xset +fp /usr/share/fonts/artwiz-fonts
xset fp rehash

# - Set background image:
# feh --bg-scale /media/data/Video/Billeder/BGs/dwm_bg2.png &
# /home/lys/bin/astronomy_potd_wallpaper.sh
#feh --bg-center /mnt/data/Video/Billeder/BGs/friendship-is-magic-fanart.png
feh --bg-center /mnt/data/Video/Billeder/BGs/this_city_needs_a_hero.jpg

# Disables screen blanking (0), suspends the screen after 6 minutes and then turns it off after 7.
# More info: http://www.shallowsky.com/linux/x-screen-blanking.html
xset dpms 0 360 420

# Disables wake on lan:
# ethtool -s eth0 wol d

# Start the urxvt daemon:
urxvtd --quiet --opendisplay --fork

# Boot numlock on:
numlockx &

# Unclutter - hide the cursor after some seconds of mouse inactivity.
exec unclutter -root &

#enable mouse keys (activate via SHIFT+NUMLOCK and disable again the same way)
setxkbmap -option keypad:pointerkeys

# Enable xbindkeys, which maps some keysyms to commands on my keyboard, so the volume and audio controls work. See ~/.xbindkeysrc
xbindkeys

#exec dwm
/home/lys/sh/startdwm.sh
